config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products
    resources :categories do
      collection do
          get :manage
          post :rebuild
      end
    end
  end
  namespace :users do
    get 'omniauth_callbacks/facebook'
    get 'omniauth_callbacks/google_oauth2'
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :pictures
  resources :products
  root to: 'visitors#index'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users
  resources :feedbacks
  resources :questions

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sent_feedbacks,     :class_name => 'Feedback',  :foreign_key => 'sender_id'
  has_many :received_feedbacks, :class_name => 'Feedback',  :foreign_key => 'receiver_id'
  has_many :sent_questions,     :class_name => 'Question',  :foreign_key => 'sender_id'
  has_many :received_questions, :class_name => 'Question',  :foreign_key => 'receiver_id'

  mount_uploader :avatar, AvatarUploader
  has_many :products
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:facebook, :google_oauth2]


  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def full_name
     "#{first_name} #{last_name}"
  end

  def set_default_role
    self.role ||= :user
  end

  def self.find_from_social_registrations_oauth(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
  	  registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(
        first_name: data["first_name"],
        last_name: data["last_name"],
        provider:access_token.provider,
        email: data["email"],
        uid: access_token.uid ,
        password: Devise.friendly_token[0,20],
        )
      end
    end
  end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def destroy
    current_user = User.find(params[:id])
    current_user.destroy
    flash[:success] = "User deleted."
    redirect_to admin_users_url
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_from_social_registrations_oauth request.env["omniauth.auth"]
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.find_from_social_registrations_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
   redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @feedback = Feedback.new
    @question = Question.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
  #  unless current_user.admin?
  #    redirect_to :back, :alert => "Access denied."
  #  end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/views/users/_user.html.haml
%td
  = link_to user.email, user
%td
  = form_for(user) do |f|
    = f.select(:role, User.roles.keys.map {|role| [role.titleize,role]})
    = f.submit 'Change Role', :class => 'button-xs'
%td
  = link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user

app/views/users/index.html.haml
.container
  .row
    %h3 Users
    .column
      %table.table
        %tbody
          - @users.each do |user|
            %tr
              = render user
              

app/views/users/show.html.haml
.body_user_page
.row
  .col-md-4
    .user_logo
      - if @user.avatar.present?
        = image_tag(@user.avatar_url)
      - else
        = image_tag ("default_picture.png")
  .col-md-4
    .user_page_name
      %h4.user_name
        = @user.full_name
    .user_page_info
      - if @user.profession.present?
        %p Profession: #{@user.profession}

      - if @user.email.present?
        %p Email: #{@user.email}

      - if @user.facebook_link.present?
        %p Facebook link: #{@user.facebook_link}

      - if @user.vk_link.present?
        %p Vk link: #{@user.vk_link}

      - if @user.google_link.present?
        %p Google link: #{@user.google_link}

      - if @user.phone_number.present?
        %p Phone number: #{@user.phone_number}

  .col-md-4
    .questions
      %h4 Ask a question:
      = simple_form_for @question do |f|
        %p
          %b
            - if user_signed_in?
              = f.text_field :user_name, value: current_user.full_name
              = f.hidden_field :sender_id, value: current_user.id
              = f.hidden_field :receiver_id, value: @user.id
            - else
              = f.text_field :user_name, placeholder: "Your name"
        %p
          %br
            = f.text_field :email, placeholder: "Email Address"
            = f.error_notification message: "Email can't be blank."
        %p
          %br
            = f.text_area :body, placeholder: "Type your question here..."
        %p
          = f.submit "Send"

.row
  .col-md-12
  - if @user.about.present?
    %p.about About:
    .about
      = @user.about

.feedbacks
  %h4 Feedbacks:
  - @user.received_feedbacks.each do |feedback|
    %p
      %strong User name:
      = feedback.sender.full_name
    %p
      %strong Feedback:
      = feedback.body
  %h4 Add a feedback:
  = simple_form_for(@feedback) do |f|
    %p
      %strong User name
      %br
        = f.text_field :user_name
        = f.hidden_field :receiver_id, value: @user.id
        = f.hidden_field :sender_id, value: current_user.id
    %p
      = f.label :body
      %br
        = f.text_area :body
    %p
      = f.submit
  = link_to 'Edit', edit_user_path(@user)
  |
  \#{link_to 'Back', users_path}