config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :products
    resources :categories do
      collection do
          get :manage
          post :rebuild
      end
    end
  end
  namespace :users do
    get 'omniauth_callbacks/facebook'
    get 'omniauth_callbacks/google_oauth2'
  end

  mount Ckeditor::Engine => '/ckeditor'
  resources :pictures
  resources :products
  root to: 'visitors#index'
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users
  resources :feedbacks
  resources :questions

end

app/models/product.rb
class Product < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :user
  has_many :pictures
  default_scope { order(id: :desc) }  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

    # GET /products
    # GET /products.json
  def index
    @products = Product.last(8)
  end

    # GET /products/1
    # GET /products/1.json
  def show
  end

    # GET /products/new
  def new
    @product = Product.new
  end

    # GET /products/1/edit
  def edit
  end

    # POST /products
    # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /products/1
    # PATCH/PUT /products/1.json
  def update

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

    # DELETE /products/1
    # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

      # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

      # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :amount, :user_id, :picture)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.last(8)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :amount, :user_id, :picture)
    end
end

app/views/admin/products/_form.html.haml
= simple_form_for [:admin, @product], :html=>{:multipart => true} do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.cktext_area :description
    = f.input :amount
    = f.file_field :picture
    = f.hidden_field :user_id, :value => current_user.id

  .form-actions
    = f.button :submit

app/views/admin/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/admin/products/index.html.haml
%h1 Listing products

%table
  %thead
    %tr
      %th Title
      %th Description
      %th Amount
      %th Picture
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr
        %td= product.title
        %td= product.description.html_safe
        %td= product.amount
        %td= image_tag(product.picture.url, :width=>100) if product.picture.present?
        %td= link_to 'Show', [:admin, product]
        %td= link_to 'Edit', edit_admin_product_path(product)
        %td= link_to 'Destroy', [:admin, product], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Product', new_admin_product_path

app/views/admin/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/admin/products/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @product.title
%p
  %b Description:
  = @product.description.html_safe
%p
  %b Amount:
  = @product.amount
%p
  %b User:
  = @product.user.full_name
%p
  %b Picture:
  .product_picture
  = image_tag(@product.picture.url) if @product.picture.present?

= link_to 'Edit', edit_admin_product_path(@product)
\|
= link_to 'Back', admin_products_path